name: CI Stage

on: 
  push:
    branches:
    - staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy Stage
      run: sh ./deploy.sh staging
